"""primeira migrate

Revision ID: 19516a0509e7
Revises: 
Create Date: 2025-03-08 13:11:16.524030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19516a0509e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fornecedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('cost_per_kwh', sa.Float(), nullable=True),
    sa.Column('min_kwh_limit', sa.Float(), nullable=True),
    sa.Column('num_clientes', sa.Integer(), nullable=True),
    sa.Column('average_rating', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fornecedor')
    # ### end Alembic commands ###
