"""create suppliers table

Revision ID: ad6dc7a0d8f3
Revises: 4ca805c7a441
Create Date: 2025-03-09 21:53:53.631887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad6dc7a0d8f3'
down_revision = '4ca805c7a441'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('cnpj', sa.String(length=20), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('cost_per_kwh', sa.Float(), nullable=False),
    sa.Column('min_kwh_limit', sa.Float(), nullable=False),
    sa.Column('num_clients', sa.Integer(), nullable=False),
    sa.Column('average_rating', sa.Float(), nullable=False),
    sa.Column('logo', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    op.drop_table('fornecedor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fornecedor',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('logo', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('estado', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('custo_kwh', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('limite_minimo_kwh', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('num_clientes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('avaliacao_media', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cnpj', sa.VARCHAR(length=18), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='fornecedor_pkey')
    )
    op.drop_table('suppliers')
    # ### end Alembic commands ###
