"""Adiciona a coluna cnpj ao fornecedor

Revision ID: 4ca805c7a441
Revises: 19516a0509e7
Create Date: 2025-03-08 13:49:39.825019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ca805c7a441'
down_revision = '19516a0509e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fornecedor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cnpj', sa.String(length=18), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fornecedor', schema=None) as batch_op:
        batch_op.drop_column('cnpj')

    # ### end Alembic commands ###
